[package]
name = "int-filter"
version = "0.1.0"
authors = ["Reiner Lange <reiner.lange@medicalsyn.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
